# Numpy tutorial

### Introduction

NumPy is a Python library.

NumPy is used for working with **arrays**.

NumPy is short for "Numerical Python".

Arrays are very frequently used in data science, where speed and resources are very important.

Recall, data Science is a field of study where we study how to store, use and analyze data for deriving information from it.

#### What is an “array”?

In computer programming, an array is a structure for storing and retrieving data.

1-D dimensional Array: Has just one row

2-D dimensional Array: A two-dimensional array would be like a table

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages.

<div>
<img src="what-is-numpy.png" style="width: 500px; height: auto; margin-left: 20px;"/>
</div>


In NumPy, this idea is generalized to an arbitrary number of dimensions, and so the fundamental array class is called ndarray.

Ndarray represents an “N-dimensional array”.

#### Restrictions in Numpy Array
1. All elements of the array must be of the same type of data.
2. Once created, the total size of the array can’t change.
3. The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

### Installing and Importing Numpy

Numpy can be installed for Mac and Linux users via the following pip command:

Install --> !pip install numpy

Import --> import numpy as np

Version --> print(np.__version__)

### Creation of Numpy

1. NumPy ndarray object by using the array() function
2. Create NumPy Array with List and Tuple
2. Create Array of Fixed Size using functions like np.zeros, np.ones, np.full, np.empty, etc

#### Uses of Numpy

<div>
<img src="OIP.png" style="width: 500px; height: auto; margin-left: 20px;"/>
</div>

In [16]:
!pip install numpy

In [1]:
#importing of libraries
import numpy as np

In [2]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Olaoluwa\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>


In [3]:
print(np.__version__)

2.1.3


### Creating Arrays in NumPy

In [4]:
#creating of array in numpy

arr = np.array([1,2,3,4])
arr5 = np.array([[1,2,3,4,5,6,7,8,9,10],
                  [2, 4, 6,8,10, 12,14,16,18,20]])
arr5
arr5.shape

(2, 10)

In [5]:
arr5

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr

array([1, 2, 3, 4])

In [8]:
#Checking the dimension of the array
arr.ndim

1

In [9]:
#Checking the shape of the array

arr.shape

(4,)

In [10]:
arr2 = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]])

#column--  0,1,2,3,4
#row0     [1,2,3,4,5]
#row1     [6,7,8,9,10]
#row2     [11,12,13,14,15]
#row3     [16,17,18,19,20]

In [11]:
#Checking for the dimension of the array

arr2.ndim

2

In [12]:
#Creating an 2D array

arr_2d = np.array([[1,2,3,4,5,6],
                   [7,8,9,10,11,12]])
arr_2d.shape

(2, 6)

In [13]:
#Creating a 2D array
arr2  = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])

print(arr2.shape)

(4, 3)


In [14]:
#Reshaping a 2D array

arr4 = arr_2d.reshape(4,3)
arr4.shape

(4, 3)

In [15]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr5 = arr2 + arr4
arr5

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [21]:
arr11 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr11.shape

(3, 5)

In [22]:
arr11

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
arr12 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])
arr12.shape

(5, 3)

In [23]:
arr13 = arr11.reshape(5,3)
arr13.shape

(5, 3)

In [24]:
arr13

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
arr14 = arr13 + arr12
arr14

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [26]:
arr11

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
arr12

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [28]:
try:
    arr11+arr12
except ValueError:
    print("It's not the same shape, Put in the correct shape")

It's not the same shape, Put in the correct shape


In [30]:
arr16 = np.zeros((5,5), dtype=int)
arr16.size

25

In [31]:
arr16

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
arr16.shape

(5, 5)

In [33]:
arr17  = np.ones((5,5), dtype=int)
arr17

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
arr18 = arr16+arr17
arr18

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
arr19 = np.eye(10)
arr19.shape

(10, 10)

In [36]:
arr19

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [38]:
np.full((10, 10), [1,2,3,4,5,6,7,8,9,10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [39]:
arr20 = np.eye(100)
arr20

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
np.ones((2, 2))


array([[1., 1.],
       [1., 1.]])

In [41]:
np.ones((2, 2), dtype=str)


array([['1', '1'],
       ['1', '1']], dtype='<U1')

#### Creating array from Random

In [42]:
#importing of libraries
import numpy as np

In [43]:
from random import random

In [45]:
# Create an array filled with random values
np.random.seed(0)
e = np.random.random((2,2))  
e

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [46]:
np.random.seed(42)
f = np.random.random((2,2))  
f

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [ ]:
array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [48]:
np.random.seed(1)
f = np.random.random((10,10))
f = f.reshape(10,10)
f

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02, 6.70467510e-01, 4.17304802e-01, 5.58689828e-01,
        1.40386939e-01, 1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01,
        8.76389152e-01, 8.94606664e-01, 8.50442114e-02, 3.90547832e-02,
        1.69830420e-01, 8.78142503e-01],
       [9.83468338e-02, 4.21107625e-01, 9.57889530e-01, 5.33165285e-01,
        6.91877114e-01, 3.15515631e-01, 6.86500928e-01, 8.34625672e-01,
        1.82882773e-02, 7.50144315e-01],
       [9.88861089e-01, 7.48165654e-01, 2.80443992e-01, 7.89279328e-01,
        1.03226007e-01, 4.47893526e-01, 9.08595503e-01, 2.93614148e-01,
        2.87775339e-01, 1.30028572e-01],
       [1.93669579e-02, 6.78835533e-01, 2.11628116e-01, 2.65546659e-01,
   

In [51]:
#Create an array of the given shape and populate it with random #samples from a uniform distribution over 0, 1
# rand is used for uniform randomness
np.random.seed(42)
g = np.random.rand(3, 2) 
g

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [52]:
#Create an array of the given shape and populate it with random #samples from a uniform distribution over 0, 1
# randn is used for normally distributed values
np.random.seed(42)
k = np.random.randn(3, 2) 
k

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696]])

In [53]:
 #generate integer
np.random.seed(42)
h = np.random.randint(0,5, size=(5,5))
h

array([[3, 4, 2, 4, 4],
       [1, 2, 2, 2, 4],
       [3, 2, 4, 1, 3],
       [1, 3, 4, 0, 3],
       [1, 4, 3, 0, 0]], dtype=int32)

In [54]:
#Checking for the size of the array
np.random.seed(42)
h = np.random.randint(0,5, size=(5,5))
h.size

25

## Array Operations and Manipulation

In [224]:
array1 = np.arange(100).reshape(10,10) 
#flat = array1.flatten()

2

In [55]:
flat

NameError: name 'flat' is not defined

In [56]:
sorted_arr = np.sort(np.array([3, 1, 2,6,4,7,8,8,10])) 
sorted_arr

array([ 1,  2,  3,  4,  6,  7,  8,  8, 10])

In [57]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
sorted_arr1 = np.sort(np.eye(5))

In [59]:
sorted_arr1

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

#### Numpy Array Indexing and Slicing

##### Indexing

- You can access or index an array element by referring to its index number.

- You can index and slice NumPy arrays in the same ways you can slice Python lists.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.



##### Slicing Rules

1. We pass slice instead of index like this: [start:end].
2. We can also define the step, like this: [start:end:step].
3. If we don't pass start its considered 0
4. If we don't pass end its considered length of array in that dimension
5. If we don't pass step its considered 1

In [60]:
#slicing
data = np.array([10, 20, 30, 40,50,60,70,80,90,100])


print(data[:])   

[ 10  20  30  40  50  60  70  80  90 100]


In [61]:
np.random.seed(42)
g = np.random.rand(3, 2) 
g

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [62]:
d = g.flatten()
d

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452])

In [63]:
d[1:5]

array([0.95071431, 0.73199394, 0.59865848, 0.15601864])

##### For more reading on Numpy 
check: https://www.w3schools.com/python/numpy/default.asp